SILVER_MARKET_FEATURES = """
CREATE OR REPLACE TABLE SILVER.MARKET_FEATURES (
    SYMBOL        VARCHAR(10)    NOT NULL,
    TIMESTAMP     TIMESTAMP_NTZ  NOT NULL,
    CLOSE         FLOAT,
    MA_20         FLOAT,
    MA_50         FLOAT,
    RSI_14        FLOAT,
    BB_UPPER      FLOAT,
    BB_MIDDLE     FLOAT,
    BB_LOWER      FLOAT,
    MACD          FLOAT,
    MACD_SIGNAL   FLOAT,
    MACD_HIST     FLOAT,
    ROC_10        FLOAT,
    VOLATILITY    FLOAT,
    PROCESSED_AT  TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP
);
"""